github.com:
    users:
        kagansozen:
            oauth_token: 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
    git_protocol: ssh
    oauth_token: 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
    user: kagansozen
